version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rsa
    versions:
    - "4.7"
    - 4.7.1
  - dependency-name: httplib2
    versions:
    - 0.18.0
